### ISSUE TITLE
Packaging the project for easier usage

### ISSUE THREAD

**Issue by farzadab** [UBCMOCCA/TerrainRLSim#1]
Hi,

I'm working on creating a `.deb` package to make it easier to install this project.
The version that I have now can be [downloaded from here](https://www.dropbox.com/s/jfcxtqfe87y63j9/terrainrlsim-pkg.deb?dl=0). To install it you might need to run the following commands:
```
sudo dpkg -i terrainrlsim-pkg.deb
sudo apt update -y
sudo apt install -f -y
```

It doesn't install the Python package yet. Also, since it's my first time doing this there might be a lot of issues such as:
  - I put the compiled files in the package which depend on installed libraries such as `boost`, but to make sure that the name of the `.so` files that they need doesn't change I used exact versions, which might cause trouble later down the road;
  - Everything was compiled on a 64bit system, so I'm not sure if it works on 32bit or not;

Any comment is appreciated.

---------------------------
The package was compiled and built on an installation of "**elementary OS 0.4.1 Loki**" and tested on a bare installation of "**Ubuntu 16.04.4** LTS (Xenial Xerus)".

**Comment by whx0822** [comment]
Hi,

Thank you for the tool. But I cannot download it from the DropBox. Are there some problems?
Thanks.

**Comment by farzadab** [comment]
Hi,
There shouldn't be any problems for downloading the package, but someone has noted that the package **doesn't work** on other versions of Ubuntu, so I wouldn't waste my time on it.
Alternatively, I have a **docker version** to avoid these problems (the link to the [Dockerfile](https://github.com/farzadab/TerrainRLSim/blob/master/docker/nodata/Dockerfile)). Installing it should be pretty straightforward, with [the instuctions](https://github.com/farzadab/TerrainRLSim/blob/master/docker/nodata/README.md), but it might take a lot of time to compile everything.

**Comment by whx0822** [comment]
Hi,
Thanks for your kindly reply. 
I have successfully downloaded the file. I follow the instruction (https://github.com/UBCMOCCA/TerrainRLSim) first. After the "make config=release64" instruction, I cannot find any executable files. Then I follow your instruction(https://github.com/UBCMOCCA/TerrainRLSim/issues/1). After that, I still cannot find any executable files. When I run "python3 simAdapter/terrainRLSimTest.py", I got the follow error message "KeyError: 'TERRAINRL_PATH'". 
Could you give me some hints? Many thanks in advance.

Thanks.

**Comment by farzadab** [comment]
The `.deb` file doesn't include the Python bindings. You need to follow the [build instructions](https://github.com/UBCMOCCA/TerrainRLSim#build-instructions) #6:
```bash
cd simAdapter/
sudo apt-get install swig3.0 python3-dev python3-pip -y
./gen_swig.sh
cd ../
```
Then [install the Python library](https://github.com/UBCMOCCA/TerrainRLSim#installing-python-library-version):
```bash
export TERRAINRL_PATH=<path_to_terrainRL>
## better set this in your "~/.bashrc"
pip3 install --user -v -e $TERRAINRL_PATH
```
Sorry for the inconvenience, I wanted to add these bindings as well, but since it turned out that the `.deb` file doesn't work correctly, I just gave up on it.

**Comment by whx0822** [comment]
Hi,
Thank you so much. Now I can use the environment in Python. I wonder how I could generate the two executable files even if I have followed the build instructions and no error message occur.
By the way, I happen to see a great paper(https://arxiv.org/pdf/1804.06424.pdf) about the environment. For beginners like me, it could be useful. 

Thanks.

**Comment by Neo-X** [comment]
:) I don't know if it is that great of a paper but thanks! The build instructions are not too complicated but they have mostly been tested/used on Ubuntu 16.04.

**Comment by whx0822** [comment]
@Neo-X Hi, after I follow the instructions, I cannot get the two executable files. It would be highly appreciated if you could give me some hints about that problem?

Thanks.

**Comment by farzadab** [comment]
The `deb` package, puts executables in your `/usr/bin`, so `./TerrainRL` becomes `TerrainRL`, and the same for the optimizer.
But if you had actually compiled everything from scratch, the executable would have been in the directory `x64/Release` of your `TERRAINRL_PATH`.

**Comment by Neo-X** [comment]
@whx0822 Which instructions are you referring to? The build instructions or the deb package?

**Comment by whx0822** [comment]
Thanks @Neo-X @farzadab . I have found the two executable files @farzadab. I follow the build instructions.
Thank you for you guys.
