### ISSUE TITLE
Undefined reference in the last step

### ISSUE THREAD

**Issue by WatsonZhou12** [UBCMOCCA/TerrainRLSim#10]
Hi!
I've tried using the latest release as you uploaded and followed strictly the build Instructions in your readme. However when I process the last step: "make config=release64", I got the following errors. 
```
~/TerrainRLSim-master/gmake$ make config=release64
==== Building terrainrlUtil (release64) ====
==== Building terrainrlAnim (release64) ====
==== Building terrainrlLearning (release64) ====
==== Building terrainrlSim (release64) ====
==== Building terrainrlRender (release64) ====
==== Building terrainrlScenarios (release64) ====
==== Building TerrainRL (release64) ====
Linking TerrainRL
../external/caffe/build/lib/libcaffe.so undefined reference to cv::imread(cv::String const&, int)
../external/caffe/build/lib/libcaffe.so undefined reference to cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)
../external/caffe/build/lib/libcaffe.so undefined reference to cv::imdecode(cv::_InputArray const&, int)
collect2: error: ld returned 1 exit status
TerrainRL.make:130: recipe for target '../x64/Release/TerrainRL' failed
make[1]: *** [../x64/Release/TerrainRL] Error 1
Makefile:16: recipe for target 'TerrainRL' failed
make: *** [TerrainRL] Error 2
```

I am using Ubuntu 16.04. I don't know why there is the undefined reference and what caused these. The release is the newest and there is no other problem before the last step. Is there anyone who could help me?
Thanks in advance! 
@Neo-X @farzadab

**Comment by WatsonZhou12** [comment]
Opencv and anaconda caused this problem.
For Opencv, I tried to uncomment the opencv in Makefile.config in order to use opencv3.2
For anaconda, I comment the .bashrc about the anaconda path.

**Comment by Neo-X** [comment]
Try recompiling caffe in the external folder. I recently updated the build script to not use any dependencies, so it should not be trying to link to OpenCV.

**Comment by WatsonZhou12** [comment]
Yeah recompiling is ok.
May I ask where is your CNN training file for terrain training and where is your state combination(robot + terrain)?
