### ISSUE TITLE
Linking error in terrainrlUtil : libjsoncpp .... relocation .... can not be used when making a shared object

### ISSUE THREAD

**Issue by wpumacay** [UBCMOCCA/TerrainRLSim#7]
Hi.

I've tried to compile the project in ubuntu 16.04, and followed the steps in the readme. I got this weird linking error when linking terrainrlUtil :

```bash
...
Linking terrainrlUtil
/usr/bin/ld: ../external/jsoncpp/build/debug/src/lib_json/libjsoncpp.a(json_value.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
../external/jsoncpp/build/debug/src/lib_json/libjsoncpp.a: error adding symbols: Bad value
```
I also got lots of warnings regarging deprecations, like (I'm using the g++ version that comes with 16.04, which is g++ 5.04): 
```bash
...
MotionDB.cpp
In file included from ../external/Eigen/Core:276:0,
                 from ../external/Eigen/Dense:1,
                 from ../util/MathUtil.h:5,
                 from ../util/MotionDB.h:11,
                 from ../util/MotionDB.cpp:8:
../external/Eigen/src/Core/Functors.h:973:28: warning: ‘template<class _Operation> class std::binder2nd’ is deprecated [-Wdeprecated-declarations]
 struct functor_traits<std::binder2nd<T> >
                            ^
In file included from /usr/include/c++/5/bits/stl_function.h:1128:0,
                 from /usr/include/c++/5/string:48,
                 from /usr/include/c++/5/random:40,
                 from ../util/MathUtil.h:3,
                 from ../util/MotionDB.h:11,
                 from ../util/MotionDB.cpp:8:
/usr/include/c++/5/backward/binders.h:143:11: note: declared here
     class binder2nd
...
```

So far I've tried the following : 

* adding the -fPIC flag as suggested by the error, but I checked in the premake file that they already set that flag in various libraries ( terrain___ ).
* changing the libraries from sharedlib to staticlib in the premake file (it worked for me once in other projects, as I was mixing static and dynamic libraries) and got to the point where everything compiled except the last steps (the main terrainRL application), which returned lots of errors with jsoncpp :
```bash
...
undefined reference to `Json::Value::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
...
```
I checked and it looked like the generated makefiles included the appropiate library directories (also jsoncpp).

Is there are different way to compile for ubuntu16.04 ?. Perhaps I'm missing something very obvious, but still I get the same results after removing and starting from scratch the whole process. Also, the external libraries seem to be all static (.a) but in the README they reference some dynamic libraries when copying from the _external_ folder. The build uses those static libraries, right?, not dynamic.

Thanks in advance.

**Comment by Neo-X** [comment]
It appears you might be using the incorrect external libraries.
Download the proper ones from [here](https://github.com/xbpeng/DeepLoco/releases/tag/0.81) that will have all the dynamic libraries. I will updated the readme.

**Comment by Neo-X** [comment]
[here](url)

**Comment by Neo-X** [comment]
It appears you might be using the incorrect external libraries.
Download the proper ones from [here](https://github.com/xbpeng/DeepLoco/releases/tag/0.81) that will have all the dynamic libraries. I will update the readme.

**Comment by wpumacay** [comment]
Hi @Neo-X . 

I've tested with the new compressed libraries from the updated README and it works fine now. Thanks! .

PD: are you updating the examples in the following commits?. Because there are some examples missing from the DeepTerrainRL repo (some missing models) and it breaks when loading (like the dog environment). Should I open another issue for this? I could give a hand by cleaning it up a bit.

**Comment by Neo-X** [comment]
We don't have models for many of the environments. This library is more meant for providing interesting simulation environments, for the purposes of learning your own policies.
