### ISSUE TITLE
where to download the library.zip

### ISSUE THREAD

**Issue by dumpinfo** [UBCMOCCA/TerrainRLSim#8]
Windows
This setup has been tested on Windows 7 and 10 with visual studio 2013.

Download the library.zip file that contains almost all of the relevant pre-compiled external libraries and source code.
Unpack this library in the same directory the project is located in. For example, TerrainRL/../.

In the compile instructions , it notes that to download the  library.zip before compiling the source code.
So, what is the download address?

**Comment by farzadab** [comment]
I think it refers to [this file](https://github.com/xbpeng/DeepLoco/releases/download/0.81/library.zip) from [this release](https://github.com/xbpeng/DeepLoco/releases/tag/0.81) which was referred to earlier.
